"""baseline schema

Revision ID: 0c7259b80246
Revises: 
Create Date: 2026-07-14 09:26:59.373432
"""
from alembic import op
import sqlalchemy as sa


revision = '0c7259b80246'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asp_registry',
    sa.Column('asp_id', sa.String(length=64), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('endpoint', sa.String(length=512), nullable=True),
    sa.Column('transport', sa.String(length=8), nullable=True),
    sa.Column('tool_schema', sa.JSON(), nullable=True),
    sa.Column('mode', sa.String(length=24), nullable=True),
    sa.Column('original_price_per_call', sa.Float(), nullable=True),
    sa.Column('thehouse_price', sa.Float(), nullable=True),
    sa.Column('max_batch_size', sa.Integer(), nullable=True),
    sa.Column('window_timer_ms', sa.Integer(), nullable=True),
    sa.Column('cache_ttl_seconds', sa.Integer(), nullable=True),
    sa.Column('break_even_batch_size', sa.Integer(), nullable=True),
    sa.Column('batch_param', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('asp_id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts_ms', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('economics_ledger',
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('asp_id', sa.String(length=64), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('window_open_ms', sa.Integer(), nullable=False),
    sa.Column('window_fire_reason', sa.String(length=16), nullable=False),
    sa.Column('target_cost_paid', sa.Float(), nullable=False),
    sa.Column('thehouse_revenue_collected', sa.Float(), nullable=False),
    sa.Column('gross_margin', sa.Float(), nullable=False),
    sa.Column('below_break_even', sa.Boolean(), nullable=True),
    sa.Column('dedup_hits', sa.Integer(), nullable=True),
    sa.Column('priority_surcharges', sa.Float(), nullable=True),
    sa.Column('split_quality', sa.String(length=8), nullable=True),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_table('payment_keys',
    sa.Column('replay_key', sa.String(length=64), nullable=False),
    sa.Column('ts_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('replay_key')
    )
    op.create_table('request_log',
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('asp_id', sa.String(length=64), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('arguments', sa.JSON(), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('caller_id', sa.String(length=128), nullable=False),
    sa.Column('priority', sa.Boolean(), nullable=True),
    sa.Column('received_at_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('merged_into', sa.String(length=64), nullable=True),
    sa.Column('batch_id', sa.String(length=64), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('charged', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('request_id')
    )
    with op.batch_alter_table('request_log', schema=None) as batch_op:
        batch_op.create_index('ix_request_log_status_received', ['status', 'received_at_ms'], unique=False)

    op.create_table('settlements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts_ms', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('counterparty', sa.String(length=128), nullable=False),
    sa.Column('amount_usdt', sa.Float(), nullable=False),
    sa.Column('scheme', sa.String(length=24), nullable=True),
    sa.Column('network', sa.String(length=24), nullable=True),
    sa.Column('tx_ref', sa.String(length=256), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('batch_id', sa.String(length=64), nullable=True),
    sa.Column('settle_status', sa.String(length=16), nullable=False),
    sa.Column('settle_txhash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settlements')
    with op.batch_alter_table('request_log', schema=None) as batch_op:
        batch_op.drop_index('ix_request_log_status_received')

    op.drop_table('request_log')
    op.drop_table('payment_keys')
    op.drop_table('economics_ledger')
    op.drop_table('audit_log')
    op.drop_table('asp_registry')
    # ### end Alembic commands ###
